'\" t
.\"     Title: opensc-tool
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 02/16/2010
.\"    Manual: OpenSC tools
.\"    Source: opensc
.\"  Language: English
.\"
.TH "OPENSC\-TOOL" "1" "02/16/2010" "opensc" "OpenSC tools"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
opensc-tool \- generic smart card utility
.SH "SYNOPSIS"
.PP

\fBopensc\-tool\fR
[OPTIONS]
.SH "DESCRIPTION"
.PP
The
\fBopensc\-tool\fR
utility can be used from the command line to perform miscellaneous smart card operations such as getting the card ATR or sending arbitrary APDU commands to a card\&.
.SH "OPTIONS"
.PP
.PP
\fB\-\-atr, \-a\fR
.RS 4
Print the Answer To Reset (ATR) of the card, output is in hex byte format
.RE
.PP
\fB\-\-serial\fR
.RS 4
Print the card serial number (normally the ICCSN), output is in hex byte format
.RE
.PP
\fB\-\-send\-apdu\fR apdu, \fB\-s\fR apdu
.RS 4
Sends an arbitrary APDU to the card in the format AA:BB:CC:DD:EE:FF\&.\&.\&.
.RE
.PP
\fB\-\-list\-files, \-f\fR
.RS 4
Recursively lists all files stored on card
.RE
.PP
\fB\-\-list\-readers, \-l\fR
.RS 4
Lists all configured readers
.RE
.PP
\fB\-\-list\-drivers, \-D\fR
.RS 4
Lists all installed card drivers
.RE
.PP
\fB\-\-list\-rdrivers, \-R\fR
.RS 4
Lists all installed reader drivers
.RE
.PP
\fB\-\-reader\fR num, \fB\-r\fR num
.RS 4
Use the given reader number\&. The default is 0, the first reader in the system\&.
.RE
.PP
\fB\-\-card\-driver\fR driver, \fB\-c\fR driver
.RS 4
Use the given card driver\&. The default is auto\-detected\&.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 4
Causes
\fBopensc\-tool\fR
to be more verbose\&. Specify this flag several times to enable debug output in the opensc library\&.
.RE
.SH "SEE ALSO"
.PP
opensc(7), opensc\-explorer(1)
