'\" t
.\"     Title: opensc-config
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 02/16/2010
.\"    Manual: OpenSC tools
.\"    Source: opensc
.\"  Language: English
.\"
.TH "OPENSC\-CONFIG" "1" "02/16/2010" "opensc" "OpenSC tools"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
opensc-config \- a tool to get information about the installed version of OpenSC
.SH "SYNOPSIS"
.PP

\fBopensc\-config\fR
[OPTIONS]
.SH "DESCRIPTION"
.PP

\fBopensc\-config\fR
is a tool that is used to get various information about the installed version of OpenSC\&. It is particularly useful in determining compiler and linker flags necessary to build programs with the OpenSC libraries\&.
.SH "OPTIONS"
.PP

\fBopensc\-config\fR
accepts the following options:
.PP
\fB\-\-version\fR
.RS 4
Print the installed version of OpenSC to standard output\&.
.RE
.PP
\fB\-\-libs\fR
.RS 4
Print the linker flags that are needed to compile a program to use the OpenSC libraries\&.
.RE
.PP
\fB\-\-cflags\fR
.RS 4
Print the compiler flags that are needed to compile a program to use the OpenSC libraries\&.
.RE
.PP
\fB\-\-prefix=PREFIX\fR
.RS 4
If specified, use PREFIX instead of the installation prefix that OpenSC was built with when computing the output for the
\fB\-\-cflags\fR
and
\fB\-\-libs\fR
options\&. This option is also used for the exec prefix if \-\-exec\-prefix was not specified\&. This option must be specified before any \-\-libs or \-\-cflags options\&.
.RE
.PP
\fB\-\-exec\-prefix=PREFIX\fR
.RS 4
If specified, use PREFIX instead of the installation exec prefix that OpenSC was built with when computing the output for the
\fB\-\-cflags\fR
and
\fB\-\-libs\fR
options\&. This option must be specified before any \-\-libs or \-\-cflags options\&.
.RE
.SH "SEE ALSO"
.PP
opensc(7)
