'\" t
.\"     Title: pkcs15-profile
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 02/16/2010
.\"    Manual: OpenSC tools
.\"    Source: opensc
.\"  Language: English
.\"
.TH "PKCS15\-PROFILE" "5" "02/16/2010" "opensc" "OpenSC tools"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pkcs15-profile \- format of profile for \fBpkcs15\-init\fR
.SH "SYNOPSIS"
.PP

.SH "DESCRIPTION"
.PP
The
\fBpkcs15\-init\fR
utility for PKCS #15 smart card personalization is controlled via profiles\&. When starting, it will read two such profiles at the moment, a generic application profile, and a card specific profile\&. The generic profile must be specified on the command line, while the card\-specific file is selected based on the type of card detected\&.
.PP
The generic application profile defines general information about the card layout, such as the path of the application DF, various PKCS #15 files within that directory, and the access conditions on these files\&. It also defines general information about PIN, key and certificate objects\&. Currently, there is only one such generic profile,
\fBpkcs15\&.profile\fR\&.
.PP
The card specific profile contains additional information required during card intialization, such as location of PIN files, key references etc\&. Profiles currently reside in
\fB@pkgdatadir@\fR
.SH "SYNTAX"
.PP
This section should contain information about the profile syntax\&. Will add this soonishly\&.
.SH "SEE ALSO"
.PP

\fBpkcs15\fR(7),
\fBpkcs15\-init\fR(1),
\fBpkcs15\-crypt\fR(1),
\fBopensc\fR(7),
