'\" t
.\"     Title: sc_app_info_t
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 02/16/2010
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"  Language: English
.\"
.TH "SC_APP_INFO_T" "3" "02/16/2010" "opensc" "OpenSC API reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sc_app_info_t \- OpenSC application structure
.SH "SYNOPSIS"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
#include <opensc\&.h>

#define SC_MAX_AID_SIZE            16

typedef struct sc_app_info {
	unsigned char aid[SC_MAX_AID_SIZE];
	size_t aid_len;
	char *label;
	sc_path_t path;
	unsigned char *ddo;
	size_t ddo_len;

	const char *desc;
	int rec_nr;
} sc_app_info_t;
			
.fi
.if n \{\
.RE
.\}
.sp
.SH "DESCRIPTION"
.PP
This structure describes a smart card application\&. It contains the following members:
.PP
\fIaid\fR
.RS 4
The applications\'s AID\&. An AID uniquely identifies an application, and consists of an RID (a 5\-byte "Registered Application Provider Identifier") and a PIX, which identifies an application by that provider\&. For example, the RID for PKCS#15 consists of the bytes A0 00 00 00 63, and the PIX is the string "PKCS\-15"\&. Thus, the AID of a PKCS#15 application on a smart card is A0 00 00 00 63 50 4B 43 53 2D 31\&.
.RE
.PP
\fIaid_len\fR
.RS 4
The length of the AID in bytes\&.
.RE
.PP
\fIlabel\fR
.RS 4
A UTF\-8 string describing the application\&.
.RE
.PP
\fIpath\fR
.RS 4
The application\'s full path on the card, starting at the MF\&.
.RE
.PP
\fIddo\fR
.RS 4
.RE
.PP
\fIddo_len\fR
.RS 4
.RE
.PP
\fIdesc\fR
.RS 4
A description of the application, if available\&.
.RE
.PP
\fIrec_nr\fR
.RS 4
If the EF(DIR) file is record\-structured, this has the record number in which this application is stored\&. Otherwise, this is \-1\&.
.RE
