'\" t
.\"     Title: sc_card_ctl
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 02/16/2010
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"  Language: English
.\"
.TH "SC_CARD_CTL" "3" "02/16/2010" "opensc" "OpenSC API reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sc_card_ctl \- Send a control command to a card
.SH "SYNOPSIS"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
#include <opensc\&.h>

int sc_card_ctl(struct sc_card *card, unsigned long cmd, void *args);

		
.fi
.if n \{\
.RE
.\}
.sp
.SH "DESCRIPTION"
.PP
This function is used to send various control commands to the smart card associated with
\fIcard\fR\&. The command is specified in
\fIcmd\fR, and any command\-specific arguments are pointed to by
\fIargs\fR\&.
.PP
Commands are specific to cards\&. For more details on which cards accept which commands, check the documentation for your card\&.
.SH "RETURN VALUE"
.PP
Returns 0 if successful, or a negative value in case of error\&.
