'\" t
.\"     Title: sc_detect_card_presence
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 02/16/2010
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"  Language: English
.\"
.TH "SC_DETECT_CARD_PRESE" "3" "02/16/2010" "opensc" "OpenSC API reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sc_detect_card_presence \- Detect presence of smart card in a reader
.SH "SYNOPSIS"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
#include <opensc\&.h>

int sc_detect_card_presence(sc_reader_t *reader, int slot_id);
		
.fi
.if n \{\
.RE
.\}
.sp
.SH "DESCRIPTION"
.PP
This function checks whether
\fIreader\fR
has a card present in
\fIslot_id\fR\&.
.SH "RETURN VALUE"
.PP
If an error occurred, the return value is a a negative OpenSC error code\&. If no card is present, 0 is returned\&. Otherwise, a positive value is returned, which is a combination of flags\&. The flag SC_SLOT_CARD_PRESENT is always set\&. In addition, if the card was exchanged, the SC_SLOT_CARD_CHANGED flag is set\&.
