'\" t
.\"     Title: sc_find_app_by_aid
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 12/18/2009
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"  Language: English
.\"
.TH "SC_FIND_APP_BY_AID" "3" "12/18/2009" "opensc" "OpenSC API reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sc_find_app_by_aid \- Find an application on a card
.SH "SYNOPSIS"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
#include <opensc\&.h>

const sc_app_info_t *sc_find_app_by_aid(sc_card_t *card,
                                        const unsigned char *aid,
                                        size_t aid_len);
		
.fi
.if n \{\
.RE
.\}
.sp
.SH "DESCRIPTION"
.PP
This function finds an application on
\fIcard\fR
by its
\fIaid\fR\&. The AID\'s length is specified in
\fIaid_len\fR\&.
.PP
Before calling this function, you MUST call
sc_enum_apps()
first\&.
.SH "RETURN VALUE"
.PP
Returns a
sc_app_info_t
structure describing the application corresponding to
\fIaid\fR, or NULL if none was found\&.
