'\" t
.\"     Title: sc_format_apdu
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 02/16/2010
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"  Language: English
.\"
.TH "SC_FORMAT_APDU" "3" "02/16/2010" "opensc" "OpenSC API reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sc_format_apdu \- Populate an APDU structure
.SH "SYNOPSIS"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
#include <opensc\&.h>

void sc_format_apdu(struct sc_card *card, sc_apdu_t *apdu,
                    int cse, int ins, int p1, int p2);
		
.fi
.if n \{\
.RE
.\}
.sp
.SH "DESCRIPTION"
.PP
This function populates the sc_apdu_t structure pointed to by
\fIapdu\fR
on
\fIcard\fR\&. It does not allocate memory\&. The
\fIcse\fR,
\fIins\fR,
\fIp1\fR
and
\fIp2\fR
parameters correspond to the respective APDU parameters as described in the ISO 7816 standard\&.
