.\"     Title: sc_get_data
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 05/07/2009
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_GET_DATA" "3" "05/07/2009" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_get_data \- Get a primitive data object from a card
.SH "SYNOPSIS"
.PP

.sp
.RS 4
.nf
#include <opensc\&.h>

int sc_get_data(sc_card_t *card, unsigned int tag,
                unsigned char *buf, size_t buflen);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function is used to retrieve a primitive data object from
\fIcard\fR\&. It corresponds to the GET DATA command in the ISO 7816 standard\&. The data is stored in
\fIbuf\fR, which is
\fIbuflen\fR
bytes long\&.
.PP
The
\fItag\fR
parameter specifies the object to be retrieved\&. Refer to the standard for the correct values to use\&.
.SH "RETURN VALUE"
.PP
Returns 0 if successful, or a negative value in case of error\&.
