'\" t
.\"     Title: sc_set_card_driver
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 12/18/2009
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"  Language: English
.\"
.TH "SC_SET_CARD_DRIVER" "3" "12/18/2009" "opensc" "OpenSC API reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sc_set_card_driver \- Force the use of a specified smart card driver
.SH "SYNOPSIS"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
#include <opensc\&.h>

int sc_set_card_driver(struct sc_context *ctx, const char *short_name);
		
.fi
.if n \{\
.RE
.\}
.sp
.SH "DESCRIPTION"
.PP
This function forces the use of a a specific card driver to be used in context
\fIctx\fR\&. The name of the driver is specified in
\fIshort_name\fR\&. Possible options are:
.RS 4
etoken
.RE
.RS 4
flex
.RE
.RS 4
cyberflex
.RE
.RS 4
gpk
.RE
.RS 4
miocos
.RE
.RS 4
mcrd
.RE
.RS 4
setcos
.RE
.RS 4
starcos
.RE
.RS 4
tcos
.RE
.RS 4
openpgp
.RE
.RS 4
jcop
.RE
.RS 4
oberthur
.RE
.RS 4
belpic
.RE
.RS 4
emv
.RE
.PP
This function only needs to be called if OpenSC fails to auto\-detect your card\&. If used, it should be called immediately after establishing a new context with
sc_establish_context(), but before doing anything else with the context\&.
.SH "RETURN VALUE"
.PP
If an error occurred, a negative value is returned indicating the error\&. Otherwise, 0 is returned\&.
