'\" t
.\"     Title: sc_write_record
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 12/18/2009
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"  Language: English
.\"
.TH "SC_WRITE_RECORD" "3" "12/18/2009" "opensc" "OpenSC API reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sc_write_record \- Write a record to a file
.SH "SYNOPSIS"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
#include <opensc\&.h>

int sc_write_record(struct sc_card *card, unsigned int record,
                    const unsigned char *buf, size_t buflen,
                    unsigned long flags);
		
.fi
.if n \{\
.RE
.\}
.sp
.SH "DESCRIPTION"
.PP
This function writes a record that is
\fIbuflen\fR
bytes long from the buffer pointed to by
\fIbuf\fR
to a record\-structured elementary file (EF) on
\fIcard\fR\&. The function corresponds to the ISO 7816 WRITE RECORD function\&. Call
sc_select_file()
first to select the file to write to\&.
.PP

\fIrecord\fR
specifies the ID of the record to be written, or, if
\fIflags\fR
is set to
SC_RECORD_BY_REC_NR, the record number\&. If
\fIrecord\fR
is set to zero, the current record will be read\&.
.PP
This function is used for newly created files only; for updating or appending to existing files, see the
sc_update_record()
and
sc_append_record()
functions, respectively\&.
.SH "RETURN VALUE"
.PP
Returns the number of bytes written if successful, or a negative value in case of error\&.
