.\"     Title: cardos\-info
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 07/16/2007
.\"    Manual: OpenSC tools
.\"    Source: opensc
.\"
.TH "CARDOS\-INFO" "1" "07/16/2007" "opensc" "OpenSC tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
cardos\-info \- displays information about Card OS\-based security tokens
.SH "SYNOPSIS"
.PP

\fBcardos\-info\fR
[OPTIONS]
.SH "DESCRIPTION"
.PP
The
\fBcardos\-info\fR
utility is used to display information about smart cards and similar security tokens based on Siemens Card/OS M4.
.SH "OPTIONS"
.PP
.PP
\fB\-\-reader\fR number, \fB\-r\fR number
.RS 3n
Display information about the token in reader number
\fInumber\fR. The default is reader 0.
.RE
.PP
\fB\-\-card\-driver\fR name, \fB\-c\fR driver
.RS 3n
Use the card driver specified by
\fIname\fR. The default is to auto\-detect the correct card driver.
.RE
.PP
\fB\-\-wait, \-w\fR
.RS 3n
Causes
\fBcardos\-info\fR
to wait for the token to be inserted into reader.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 3n
Causes
\fBcardos\-info\fR
to be more verbose. Specify this flag several times to enable debug output in the opensc library.
.RE
.SH "SEE ALSO"
.PP
opensc(7)
