.\"     Title: pkcs15\-tool
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 09/10/2007
.\"    Manual: OpenSC tools
.\"    Source: opensc
.\"
.TH "PKCS15\-TOOL" "1" "09/10/2007" "opensc" "OpenSC tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pkcs15\-tool \- utility for manipulating PKCS #15 data structures on smart cards and similar security tokens
.SH "SYNOPSIS"
.PP

\fBpkcs15\-tool\fR
[OPTIONS]
.SH "DESCRIPTION"
.PP
The
\fBpkcs15\-tool\fR
utility is used to manipulate the PKCS #15 data structures on smart cards and similar security tokens. Users can list and read PINs, keys and certificates stored on the token. User PIN authentication is performed for those operations that require it.
.SH "OPTIONS"
.PP
.PP
\fB\-\-learn\-card, \-L\fR
.RS 3n
Cache PKCS #15 token data to the local filesystem. Subsequent operations are performed on the cached data where possible. If the cache becomes out\-of\-sync with the token state (eg. new key is generated and stored on the token), the cache should be updated or operations may show stale results.
.RE
.PP
\fB\-\-read\-certificate\fR \fIcert\fR, \fB\-r\fR \fIcert\fR
.RS 3n
Reads the certificate with the given id.
.RE
.PP
\fB\-\-list\-certificates, \-c\fR
.RS 3n
Lists all certificates stored on the token.
.RE
.PP
\fB\-\-list\-pins\fR
.RS 3n
Lists all PINs stored on the token. General information about each PIN is listed (eg. PIN name). Actual PIN values are not shown.
.RE
.PP
\fB\-\-change\-pin\fR
.RS 3n
Changes a PIN stored on the token. User authentication is required for this operation.
.RE
.PP
\fB\-\-unblock\-pin, \-u\fR
.RS 3n
Unblocks a PIN stored on the token. Knowledge of the Pin Unblock Key (PUK) is required for this operation.
.RE
.PP
\fB\-\-list\-keys, \-k\fR
.RS 3n
Lists all private keys stored on the token. General information about each private key is listed (eg. key name, id and algorithm). Actual private key values are not displayed.
.RE
.PP
\fB\-\-list\-public\-keys\fR
.RS 3n
Lists all public keys stored on the token, including key name, id, algorithm and length information.
.RE
.PP
\fB\-\-read\-public\-key\fR \fIid\fR
.RS 3n
Reads the public key with id
\fIid\fR, allowing the user to extract and store or use the public key.
.RE
.PP
\fB\-\-read\-ssh\-key\fR \fIid\fR
.RS 3n
Reads the public key with id
\fIid\fR, writing the output in format suitable for $HOME/.ssh/authorized_keys.
.RE
.PP
\fB\-\-output\fR \fIfilename\fR, \fB\-o\fR \fIfilename\fR
.RS 3n
Specifies where key output should be written. If
\fIfilename\fR
already exists, it will be overwritten. If this option is not given, keys will be printed to standard output.
.RE
.PP
\fB\-\-no\-cache\fR
.RS 3n
Disables token data caching.
.RE
.PP
\fB\-\-pin\-id\fR \fIpin\fR, \fB\-a\fR \fIpin\fR
.RS 3n
Specifies the auth id of the PIN to use for the operation. This is useful with the \-\-change\-pin operation.
.RE
.PP
\fB\-\-reader\fR \fInum\fR
.RS 3n
Forces
\fBpkcs15\-tool\fR
to use reader number
\fInum\fR
for operations. The default is to use reader number 0, the first reader in the system.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 3n
Causes
\fBpkcs15\-tool\fR
to be more verbose. Specify this flag several times to enable debug output in the OpenSC library.
.RE
.SH "SEE ALSO"
.PP
opensc(7), pkcs15\-init(1), pkcs15\-crypt(1)
