.\"     Title: sc_asn1_entry
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 09/10/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_ASN1_ENTRY" "3" "09/10/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_asn1_entry \- OpenSC ASN1 entry structure
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

struct sc_asn1_entry {
	const char *name;
	unsigned int type;
	unsigned int tag;
	unsigned int flags;
	void *parm;
	void *arg;
};
			
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This structure describes an ASN1 entry structure. It contains the following members:
.PP
name
.RS 3n
.RE
.PP
type
.RS 3n
.RE
.PP
tag
.RS 3n
.RE
.PP
flags
.RS 3n
.RE
.PP
parm
.RS 3n
.RE
.PP
arg
.RS 3n
.RE
