.\"     Title: sc_base64_decode
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 07/16/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_BASE64_DECODE" "3" "07/16/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_base64_decode \- Decode a base64 stream
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

int sc_base64_decode(const char *inbuf,
                     unsigned char *outbuf, size_t outlen);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function decodes the base64 stream in
\fIinbuf\fR, which is NULL\-terminated, to the buffer pointed to by
\fIoutbuf\fR
(which is
\fIoutlen\fR
bytes long);
.SH "RETURN VALUE"
.PP
Returns 0 if successful, or a negative value in case of error.
