.\"     Title: sc_create_file
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 07/16/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_CREATE_FILE" "3" "07/16/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_create_file \- Create a file object
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

int sc_create_file(sc_card_t *card, sc_file_t *file);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function creates a file on
\fIcard\fR. The
\fIfile\fR
must have been created with a call to
sc_file_new()
beforehand.
