.\"     Title: sc_delete_file
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 09/10/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_DELETE_FILE" "3" "09/10/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_delete_file \- Delete a file
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

int sc_delete_file(struct sc_card *card, const struct sc_path *path);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function deletes a file specified by
\fIpath\fR
on
\fIcard\fR.
.SH "RETURN VALUE"
.PP
Returns 0 if successful, or a negative value in case of error.
