.\"     Title: sc_file_t
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 07/16/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_FILE_T" "3" "07/16/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_file_t \- OpenSC file structure
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

typedef struct sc_file {
    struct sc_path    path;
    int               type, ef_structure;
    size_t            size;
    int               id;

    /* record structured files only */
    int               record_length;
    int               record_count;
} sc_file_t;
            
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This structure describes a file object on a smart card. It contains the following members:
.PP
path
.RS 3n
This is full the path to the file, starting at the MF.
.RE
.PP
type
.RS 3n
This is the file type. It can be one of
SC_FILE_TYPE_DF,
SC_FILE_TYPE_WORKING_EF, or
SC_FILE_TYPE_INTERNAL_EF. The latter is used by some cards only, and you normally shouldn't have to deal with these files.
.RE
.PP
ef_structure
.RS 3n
For elementary files (EFs), this field describes the file's structure. It can be one of:
.IP "" 3n
SC_FILE_EF_TRANSPARENT
.IP "" 3n
SC_FILE_EF_LINEAR_FIXED
.IP "" 3n
SC_FILE_EF_LINEAR_FIXED_TLV
.IP "" 3n
SC_FILE_EF_LINEAR_VARIABLE
.IP "" 3n
SC_FILE_EF_LINEAR_VARIABLE_TLV
.IP "" 3n
SC_FILE_EF_CYCLIC
.IP "" 3n
SC_FILE_EF_CYCLIC_TLV
.IP "" 3n
SC_FILE_EF_UNKNOWN
.RE
.PP
size
.RS 3n
gives the file's size in bytes.
.RE
.PP
id
.RS 3n
gives the file's ID, as a 16\-bit number.
.RE
.PP
record_count, record_length
.RS 3n
For record structured files,
record_sount
specifies the number of records in the file. For files with fixed length records,
record_length
contains the record length.
.RE
