.\"     Title: sc_find_pkcs15_app
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 07/16/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_FIND_PKCS15_APP" "3" "07/16/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_find_pkcs15_app \- Find a PKCS#15 application on a card
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

const sc_app_info_t *sc_find_pkcs15_app(sc_card_t *card);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function attempts to find a PKCS#15 application on
\fIcard\fR. Currently, this means either a standard PKCS#15 implementation or a Belgian eID.
.PP
Before calling this function, you MUST call
sc_enum_apps()
first.
.SH "RETURN VALUE"
.PP
Returns a
sc_app_info_t
structure describing the PKCS#15 application, or NULL if none was found.
