.\"     Title: sc_file_free
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 09/10/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_FILE_FREE" "3" "09/10/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_file_free \- Free file object
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

void sc_file_free(sc_file_t *file);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function releases a file object previously allocated by
sc_select_file().
