.\"     Title: sc_read_record
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 07/16/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_READ_RECORD" "3" "07/16/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_read_record \- Read a record from a file
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

int sc_read_record(struct sc_card *card, unsigned int record,
                   unsigned char *buf, size_t buflen,
                   unsigned long flags);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function reads a record\-structured elementary file (EF) from
\fIcard\fR. The function corresponds to the ISO 7816 READ RECORD function. Call
sc_select_file()
first to select the file to read from.
.PP

\fIrecord\fR
specifies the ID of the record to be read, or, if
\fIflags\fR
is set to
SC_RECORD_BY_REC_NR, the record number. If
\fIrecord\fR
is set to zero, the current record will be read.
.PP
The read data is stored in
\fIbuf\fR, which is
\fIbuflen\fR
bytes long.
.SH "RETURN VALUE"
.PP
Returns the number of bytes read if successful, or a negative value in case of error.
