.\"     Title: sc_select_file
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 05/04/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_SELECT_FILE" "3" "05/04/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_select_file \- Select a file on a smart card
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

int sc_select_file(sc_card_t *card,
                   const sc_path_t *path,
                   sc_file_t **result);

		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function selects the file specified by
\fIpath\fR. If
\fIpath\fR
specifies a file within the currently selected DF, sc_select_file() will
\fInot\fR
select the MF first, but interpret the path relative to the current DF. It does this in order to prevent losing any authorizations previously established with the card (e.g. by presenting a PIN).
.PP
If
\fIresult\fR
is not NULL, an
sc_file_t
object is created, and the pointer to this object is stored in the location pointed to by
\fIresult\fR. This handle should later be released using
sc_file_free().
.SH "RETURN VALUE"
.PP
If an error occurred, a negative error code is returned. Otherwise, the function will return 0.
