.\"     Title: sc_set_card_driver
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 09/10/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_SET_CARD_DRIVER" "3" "09/10/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_set_card_driver \- Force the use of a specified smart card driver
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

int sc_set_card_driver(struct sc_context *ctx, const char *short_name);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function forces the use of a a specific card driver to be used in context
\fIctx\fR. The name of the driver is specified in
\fIshort_name\fR. Possible options are:
.IP "" 3n
etoken
.IP "" 3n
flex
.IP "" 3n
cyberflex
.IP "" 3n
gpk
.IP "" 3n
miocos
.IP "" 3n
mcrd
.IP "" 3n
setcos
.IP "" 3n
starcos
.IP "" 3n
tcos
.IP "" 3n
openpgp
.IP "" 3n
jcop
.IP "" 3n
oberthur
.IP "" 3n
belpic
.IP "" 3n
emv
.PP
This function only needs to be called if OpenSC fails to auto\-detect your card. If used, it should be called immediately after establishing a new context with
sc_establish_context(), but before doing anything else with the context.
.SH "RETURN VALUE"
.PP
If an error occurred, a negative value is returned indicating the error. Otherwise, 0 is returned.
