.\"     Title: sc_strerror
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 05/04/2007
.\"    Manual: OpenSC API reference
.\"    Source: opensc
.\"
.TH "SC_STRERROR" "3" "05/04/2007" "opensc" "OpenSC API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sc_strerror \- Return string describing error code
.SH "SYNOPSIS"
.PP

.sp
.RS 3n
.nf
#include <opensc.h>

const char *sc_strerror(int error);
		
.fi
.RE
.sp
.SH "DESCRIPTION"
.PP
This function returns a string describing
\fIerror\fR. It may be used with a negative errorcode returned by any OpenSC function call.
