debian/tmp/usr/include/*
debian/tmp/usr/lib/lib*.a
debian/tmp/usr/lib/libopensc.so
debian/tmp/usr/lib/libopensc.la
debian/tmp/usr/lib/libpkcs15init.so
debian/tmp/usr/lib/libpkcs15init.la
debian/tmp/usr/lib/libscconf.so
debian/tmp/usr/lib/libscconf.la
debian/tmp/usr/lib/libscldap.so
debian/tmp/usr/lib/libscldap.la
debian/tmp/usr/bin/opensc-config
debian/tmp/usr/lib/pkgconfig
debian/tmp/usr/share/man/man1/opensc-config.1
debian/tmp/usr/share/man/man3/*
debian/tmp/usr/lib/pkcs11/*.a
debian/tmp/usr/lib/pkcs11/libpkcs11.so
debian/tmp/usr/lib/pkcs11/libpkcs11.la

