debian/tmp/usr/lib/libopensc.so.*
debian/tmp/usr/lib/libpkcs15init.so.*
debian/tmp/usr/lib/libscconf.so.*
debian/tmp/etc/opensc/*.profile
debian/tmp/usr/share/opensc/*.profile
debian/tmp/usr/lib/pkcs11/opensc-pkcs11.so
debian/tmp/usr/lib/pkcs11/opensc-pkcs11.la
debian/tmp/usr/lib/pkcs11/pkcs11-spy.so
debian/tmp/usr/lib/pkcs11/pkcs11-spy.la
debian/tmp/usr/lib/pkcs11/libpkcs11.so.*
etc/opensc.conf etc/opensc
