

debian/tmp/usr/bin/cardos-tool
debian/tmp/usr/bin/cryptoflex-tool
debian/tmp/usr/bin/dnie-tool
debian/tmp/usr/bin/eidenv
debian/tmp/usr/bin/iasecc-tool
debian/tmp/usr/bin/netkey-tool
debian/tmp/usr/bin/openpgp-tool
debian/tmp/usr/bin/opensc-explorer
debian/tmp/usr/bin/opensc-tool
debian/tmp/usr/bin/piv-tool
debian/tmp/usr/bin/pkcs11-tool
debian/tmp/usr/bin/pkcs15*
debian/tmp/usr/bin/sc-hsm-tool
debian/tmp/usr/bin/westcos-tool
debian/tmp/usr/share/man/man1/cardos-tool.1
debian/tmp/usr/share/man/man1/cryptoflex-tool.1
debian/tmp/usr/share/man/man1/eidenv.1
debian/tmp/usr/share/man/man1/iasecc-tool.1
debian/tmp/usr/share/man/man1/netkey-tool.1
debian/tmp/usr/share/man/man1/openpgp-tool.1
debian/tmp/usr/share/man/man1/opensc-explorer.1
debian/tmp/usr/share/man/man1/opensc-tool.1
debian/tmp/usr/share/man/man1/piv-tool.1
debian/tmp/usr/share/man/man1/pkcs11-tool.1
debian/tmp/usr/share/man/man1/pkcs15*.1
debian/tmp/usr/share/man/man1/sc-hsm-tool.1
debian/tmp/usr/share/man/man1/westcos-tool.1
debian/tmp/usr/share/man/man5/*
debian/tmp/usr/share/opensc/*.profile
etc/opensc.conf etc/opensc
